name: Verify (dependabot)

on:
  pull_request_target:
    branches:
      - main

jobs:
  build:
    if: github.actor == 'dependabot[bot]'
    name: Verify Build
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
